# Generated by Django 2.2.5 on 2021-04-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210405_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='isntant_book',
            new_name='instant_book',
        ),
    ]
