# Generated by Django 2.2.5 on 2021-04-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210407_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='chech_in',
            new_name='check_in',
        ),
    ]
